### ISSUE TITLE
[Android] Open preferences method on Android

### ISSUE THREAD

**Issue by paintedbicycle** [joshuapinter/react-native-unified-contacts#54]
On iOS there is a method to open preferences where the user can change the permission settings. This is because if a user says no the first time, they can't do it in the app every again.

We should add this to Android to have parity.

**Comment by joshuapinter** [comment]
Fixed in 49b4967a41b851263b1838ecfa0a53babea62eb6!

Android doesn't allow you to open the Permission settings but it allows you to open the app's settings page and the Permissions is right there. 

![openprivacysettings](https://user-images.githubusercontent.com/180819/39850668-d91124de-53cf-11e8-845f-b71a0e8c1c31.gif)
